"""Add confirmed and confirmed_on fields to User model

Revision ID: 05325dd6c12a
Revises: 6cdd2033a109
Create Date: 2025-08-19 23:22:41.318318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05325dd6c12a'
down_revision = '6cdd2033a109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed_on')
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
