"""Add unique constraint to PictogramList on user_id and list_name

Revision ID: 19ced75c39c5
Revises: 6cdd2033a109
Create Date: 2025-08-18 15:57:10.551257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ced75c39c5'
down_revision = '6cdd2033a109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pictogram_list', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_id_list_name_uc', ['user_id', 'list_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pictogram_list', schema=None) as batch_op:
        batch_op.drop_constraint('_user_id_list_name_uc', type_='unique')

    # ### end Alembic commands ###
