"""Add PrintOption model

Revision ID: 2686fc1c22ae
Revises: f7c5798ffbe8
Create Date: 2026-09-18 22:42:27.256411

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2686fc1c22ae'
down_revision = 'f7c5798ffbe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_option_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_option_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_option_user_id'))
        batch_op.drop_index(batch_op.f('ix_print_option_is_public'))

    op.drop_table('print_option')
    # ### end Alembic commands ###
