"""Add unique constraint for user tree names

Revision ID: 653f145dba1f
Revises: 6a3ac1f3899f
Create Date: 2025-08-10 22:31:05.253491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653f145dba1f'
down_revision = '6a3ac1f3899f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_id_name_uc', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_constraint('_user_id_name_uc', type_='unique')

    # ### end Alembic commands ###
