"""Add pictogram_list table and add timestamps to tree

Revision ID: 6cdd2033a109
Revises: 653f145dba1f
Create Date: 2025-08-11 00:56:36.115949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdd2033a109'
down_revision = '653f145dba1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictogram_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pictogram_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pictogram_list_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_pictogram_list_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('pictogram_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pictogram_list_user_id'))
        batch_op.drop_index(batch_op.f('ix_pictogram_list_is_public'))

    op.drop_table('pictogram_list')
    # ### end Alembic commands ###
