"""Enforce not null constraints and increase password hash size

Revision ID: 972b122cad5f
Revises: bcf710f6d47f
Create Date: 2026-03-18 04:32:31.559002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972b122cad5f'
down_revision = 'bcf710f6d47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
