"""add root_id and root_url to Tree

Revision ID: bcf710f6d47f
Revises: 1e795adc5dd3
Create Date: 2026-03-16 23:56:35.630053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf710f6d47f'
down_revision = '1e795adc5dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('root_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_column('root_url')
        batch_op.drop_column('root_id')

    # ### end Alembic commands ###
