"""Add Profile and ProfileTree models

Revision ID: efaa19ed33d4
Revises: 972b122cad5f
Create Date: 2026-05-12 03:18:35.421128

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'efaa19ed33d4'
down_revision = '972b122cad5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('remote_avatar_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_user_id'), ['user_id'], unique=False)

    op.create_table('profile_tree_cross_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('colorCode', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['tree_id'], ['tree.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_tree_cross_ref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_tree_cross_ref_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_tree_cross_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_tree_cross_ref_profile_id'))

    op.drop_table('profile_tree_cross_ref')
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_user_id'))

    op.drop_table('profile')
    # ### end Alembic commands ###
