"""add image_hash and updated_at

Revision ID: f7c5798ffbe8
Revises: efaa19ed33d4
Create Date: 2026-06-04 05:03:55.256509

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f7c5798ffbe8'
down_revision = 'efaa19ed33d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('image_hash')

    # ### end Alembic commands ###
