      
# Nom du workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Déploiement en Production

# Déclencheurs du workflow
on:
  # Se déclenche automatiquement à chaque push sur la branche 'main'
  push:
    branches: [ main ]
  
  # Permet de lancer ce workflow manuellement depuis l'interface GitHub
  workflow_dispatch:

# Définit les tâches (jobs) à exécuter
jobs:
  deploy:
    # Le nom de la tâche qui apparaîtra sur GitHub
    name: Déploiement sur le serveur
    
    # Le type de machine sur laquelle la tâche va s'exécuter (fournie par GitHub)
    runs-on: ubuntu-latest

    # Les étapes (steps) de la tâche
    steps:
      # 1. Récupération du code
      # Utilise une action officielle pour récupérer le code de votre dépôt
      - name: Récupération du code source
        uses: actions/checkout@v4

      # 2. Déploiement via SSH
      # Utilise l'action populaire "SSH Action" pour se connecter et exécuter des commandes
      - name: Déploiement sur le serveur via SSH
        uses: appleboy/ssh-action@v1.0.3 # Utilisation d'une version stable
        with:
          # L'adresse IP ou le nom d'hôte de votre serveur
          host: ${{ secrets.SSH_HOST }}
          
          # Le nom de l'utilisateur de déploiement
          username: ${{ secrets.SSH_USERNAME }}
          
          # La clé SSH privée pour l'authentification
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # Le script à exécuter sur le serveur distant
          script: |
            # Aller dans le dossier de build
              cd /home/deploy-github/app/picto-three

            # Mettre à jour le code
              git fetch --all
              git reset --hard origin/main
            
            # Installer les dépendances dans le venv
              cd /home/deploy-github/app/picto-three
              if [ ! -d "venv" ]; then
                python3 -m venv venv
              fi

              source venv/bin/activate
              pip install -r requirements.txt
              pip install --upgrade pip
              pip install gunicorn
              deactivate
              

            # Synchroniser le code vers /var/www/picto-three
              sudo rsync -a --delete /home/deploy-github/app/ /var/www/
              sudo chown -R deploy:deploy /var/www/picto-three/

            # Redémarrer le service
              sudo systemctl restart picto-three.service

    
